theme: jekyll-theme-leap-day
title: Corso Java Base
description: Collezione di esercizi e tutorial per apprendere il linguaggio di programmazione Java
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
