theme: jekyll-theme-leap-day
title: [The title of your site]
description: [A short description of your site's purpose]
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - README.md
  - README2.md
